### ISSUE TITLE
where is the DomainAdversarialNet

### ISSUE THREAD

**Issue by li-ju-bazhong** [ashok-arjun/Zero-Shot-Sketch-Based-Image-Retrieval#3]
In your train.py, [from model.net import BasicModel, DomainAdversarialNet]， but actually , there is no DomainAdversarialNet in the net.py file. So please check it and reload. Thanks for your working. It's facinating.

**Comment by Alex-JYJ** [comment]
I have the same problem, and the dataset downloaded from the link is not Sketchy, maybe you can give another available link to download the dataset. Thanks!

**Comment by ashok-arjun** [comment]
@li-ju-bazhong I have updated it. Please check now.
@Alex-JYJ  - I have updated the data download instructions
