### ISSUE TITLE
What are the embeddings? 

### ISSUE THREAD

**Issue by Rukmini-Meda** [ashok-arjun/Zero-Shot-Sketch-Based-Image-Retrieval#4]
In your implementation, you used two files train_embeddings.npy and test_embeddings.npy for loading, finding the distance and computing the negative samples for the model. But how are these embeddings obtained? Are these features obtained from images in the data using the basic model? Or are these features obtained from class labels? Can you elaborate on that, please?

**Comment by ashok-arjun** [comment]
@Rukmini-Meda - those are word embeddings of the label. I used a 300 dimensional word2vec embedding for each class.
